export const ASYNC_STORAGE_CONSTANTS = {
    BUILD_NUMBER: "buildNumber",

    /* Constants used for Settings Page */
    SETTINGS_SAVED_ONCE:"settingsSavedOnce",
    SETTINGS_PORT: "port",
    SERVER_OFFSET: "serverTimezoneOffset",
    SETTINGS_SERVER: "server",
    SELECTED_SERVER_OPTION: 'selectedServerOption',
    SETTINGS_SITE_CODE: "siteCode",
    Mobile_Schedule_ID : "Mobile_Schedule_ID",
    USER_ID:"userID",
    USER_NAME:"userName",
    USER_FULL_NAME:"fullName",
    COMMUNITY_NAME : 'CommunityName',
    COMMUNITY_CODE : 'CommunityCode',
    LIST_PROVIDER : 'ProviderList',
    ASSIGNED_BY_UNIT : 'assignedByUnit',
    UNCONFIRMED_VITALS : 'unconfirmedVitals',
    SESSION_DATA: 'sessionData',
    SESSION_DATA_SET: "sessionDataSet",
    SERVICE_TIME_CODES: "serviceTimeCodes",
    LAST_SYNC_TIME: 'lastSyncTime',
    LAST_SYNC_TIME_MILLIS: 'lastSyncTimeMillis',
    WAK_SESSION_ID: 'wSessionID',
    COMPANY: 'company',
    APP_DOMAIN: 'appDomain',
    SELECTED_RES_NUMBER:'selectedResNumber',
    SELECTED_RES_NAME :'selectedName',
    PROVIDER_SHIFT_RANGE_START: 'providerShiftRangeStart',
    PROVIDER_SHIFT_RANGE_END: 'providerShiftRangeEnd',
    SELECTED_RES_OBJECT: 'SELECTED_RES_OBJECT',
    PROVIDER_LIST_LENGTH: 'providerListLength',
    COMMUNITY_LIST_LENGTH: 'communityListLength'
};