export const PRE_POUR_DIALOG_ACTION = {
    SET_SELECTED_NAME:'SET_SELECTED_NAME',
 	PREPOUR_SELECTED:'PREPOUR_SELECTED',
    SET_PRE_POUR_TIME:'SET_PRE_POUR_TIME',
    HIDE_PRN: 'HIDE_PRN',
    CHANGE_PREPOUR_DATE: 'CHANGE_PREPOUR_DATE'
    //SELECTED_COMMUNITY: 'SELECTED_COMMUNITY'
};

export const MED_PROVIDER_ACTION = {
    SET_MED_PROVIDER: 'SET_MED_PROVIDER',
    IS_PROVIDER_MOUNTED:'IS_PROVIDER_MOUNTED',
    SET_MED_PROVIDER_SHIFT_RANGE:'SET_MED_PROVIDER_SHIFT_RANGE'
};

export const SCHEDULED_DETAIL_ACTION = {
    SET_SCHEDULED_MED_COUNT : 'SET_SCHEDULED_MED_COUNT',
};

export const PRN_DETAIL_ACTION = {
    SET_PRN_MED_COUNT : 'SET_PRN_COUNT',
    SET_RECENT_PRN_MED_COUNT:'SET_RECENT_PRN_MED_COUNT'
};

export const ALLERGIES_ACTION = {
    SET_ALLERGIES_COUNT : 'SET_ALLERGIES_COUNT',
};

export const COMMUNITY_ACTION ={
    IS_COMMUNITY_MOUNTED: 'IS_COMMUNITY_MOUNTED',
    SELECTED_COMMUNITY: 'SELECTED_COMMUNITY',
    PROVIDER_SHIFT: 'PROVIDER_SHIFT'
};

export const RESIDENT_ACTION ={
    SELECTED_RESIDENT: 'SELECTED_RESIDENT'
};

export const FORM_OVERLAY_ACTION = {
    SET_REFILL_STATUS : 'SET_REFILL_STATUS',
};